# Generated by Django 4.2.7 on 2023-11-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_premio', models.CharField(max_length=100)),
                ('descripcion_premio', models.TextField()),
                ('imagen_premio', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rifa', models.CharField(max_length=100)),
                ('descripcion_rifa', models.TextField()),
                ('fecha_inicio_rifa', models.DateField()),
                ('fecha_termino_rifa', models.DateField()),
                ('cantidad_numeros_rifa', models.PositiveIntegerField()),
                ('estado_rifa', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('telefono_cliente', models.PositiveIntegerField()),
                ('numeros_comprados', models.CharField(max_length=10)),
                ('codigo_pago', models.CharField(max_length=50)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rifa')),
            ],
        ),
    ]
