# Generated by Django 4.2.7 on 2023-11-22 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_premio_rifa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='numeros_comprados',
        ),
        migrations.AlterField(
            model_name='premio',
            name='imagen_premio',
            field=models.ImageField(blank=True, null=True, upload_to='premios/'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='estado_rifa',
            field=models.CharField(choices=[('oculta', 'Oculta'), ('disponible', 'Disponible'), ('finalizada', 'Finalizada'), ('anulada', 'Anulada')], default='disponible', max_length=10),
        ),
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.compra')),
            ],
        ),
    ]
