# Generated by Django 4.2.7 on 2023-11-24 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_compra_numeros_comprados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='rifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rifa'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='imagen_premio',
            field=models.ImageField(blank=True, null=True, upload_to='premios'),
        ),
    ]
