# Generated by Django 4.2.7 on 2023-11-24 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_compra_rifa_alter_premio_rifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='numero',
            name='rifa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.rifa'),
            preserve_default=False,
        ),
    ]
