# Generated by Django 4.2.7 on 2023-11-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_numero_rifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
