# Generated by Django 4.2.7 on 2023-11-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_compra_email_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado_pago',
            field=models.CharField(blank=True, choices=[('pagado', 'Pagado'), ('reservado', 'Reservado')], max_length=10, null=True),
        ),
    ]
