# Generated by Django 4.2.7 on 2023-11-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_numero_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numero',
            name='estado_pago',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
