# Generated by Django 4.2.7 on 2023-11-27 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_numero_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='comprador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.compra'),
        ),
    ]
